version: "3"

services:
  app:
    build: .
    container_name: Nodemon
    command: npm start
    ports:
      - "5500:5500"
    volumes:
      - .:/app
    
  db:
    image: mysql:8.0.21
    hostname: mysql
    container_name: mysql_test
    ports:
      - "3310:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    
    
    
  
    